#!/usr/bin/env perl
#(shebang is for syntax highlighting)

# Always generate PDF using pdflatex
$pdf_mode = 1;

# Add PythonTeX rules via pythontexfigures
eval `python3 -m pythontexfigures.latexmkrc`
