#!/usr/bin/env perl
#(shebang is for syntax highlighting)

# Always generate PDF using pdflatex
$pdf_mode = 1;


###############################################################################
#                              PythonTeX support                              #
###############################################################################

# Delete PythonTeX generated files on latexmk -c
$clean_ext .= " pythontex-files-%R/* pythontex-files-%R";
push @generated_exts, 'pytxcode';

# Delete generated figures on latexmk -c
# TODO: Doesn't work
$clean_ext .= " figures/* figures";

# Add rule to process .pytxcode files (generated by pythontex.sty) using pythontex3.py
$extra_rule_spec{'pythontex'}  = ['internal', '', 'mypythontex', "%Y%R.pytxcode", "%Ypythontex-files-%R/%R.pytxmcr", "%R", 1];
sub mypythontex {
    # Run pythontex3.py
    my $pythontex_command = 'pythontex --interpreter python:python3 --verbose %O %S';
    my $ret = Run_subst($pythontex_command, 2);
    
    # Run this rule when any script in the scripts folder or any file in the data
    # folder is modified.  Newly created files will only be monitored after an
    # already-monitored file is modified (so this rule runs again).
    my @depend_files = glob('scripts/*.py data/*');
    foreach my $file (@depend_files){
        rdb_ensure_file($rule, $file);
        print "Depending on $file\n";
    }
    # TEMP: Run this rule when python_figures.py is modified
    rdb_ensure_file($rule, "python_figures.py");

    # The latexmk PythonTeX example rcfile at 
    # http://mirror.aut.ac.nz/CTAN/support/latexmk/example_rcfiles/pythontex-latexmkrc
    # implies that PythonTeX prints dependency information in .pytxmcr files and uses
    # that to add dependencies, but as far as I can tell it doesn't and never has.
    return $ret;
}
