version: 2.1

jobs:
  check:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip3 install pre-commit
            pre-commit run --all-files --verbose --show-diff-on-failure
  build:
    docker:
      - image: mjenz/texlive:bionic-vanilla
    environment:
      PATH: '/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    steps:
      - checkout
      - run:
          command: |
            pip3 install -e .
            python3 -m pythontexfigures.install TEXMFLOCAL
            tlmgr install subfiles
      - run:
          command: |
            pip3 install pytest
            pytest
      - store_artifacts:
          path: tests/output

workflows:
  version: 2
  check_and_build:
    jobs:
      - check
      - build
