version: 2.1

jobs:
  build:
    docker:
      - image: mjenz/texlive:bionic-vanilla
    environment:
      PATH: '/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    steps:
      - checkout
      - run:
          command: |
            pip3 install -e .
            python3 -m pythontexfigures.install TEXMFLOCAL
      - run:
          command: |
            pip3 install pytest
            pytest
